Feat/auth page
windingtree/win-stays pull request #51
Opened 2022-05-17 08:12 UTC by bobetbat

https://github.com/windingtree/win-stays/issues/41

- Login page components
- get/refresh auth hooks

2022-05-17 08:46 UTC, kostysh commented on packages/lpms-web/src/hooks/useGetAuth.ts
> +const API_URL = "http://localhost:8080/auth/";
recommend moving API_URL configuration to the app config provided via .env

2022-05-17 08:48 UTC, kostysh commented on packages/lpms-web/src/hooks/useRefreshAuth.ts
> +const API_URL = "http://localhost:8080/refreshauth/";
the same as for the previous comment. this definition must be moved to the app config. Initialization should be made via .env

2022-05-17 08:50 UTC, kostysh commented on packages/lpms-web/src/pages/Login.tsx
> +  return (
Recommend to handle the case when a user is already logged in. In this case it will be better to display a proper message and `log-out` form instead of `log-in`

2022-05-17 08:53 UTC, kostysh commented on packages/lpms-web/src/store/reducer.ts
> +    token: '',
do we really need to initialize `token` and `refreshToken` with empty strings? Why not make these properties optional in not initialize them at all.

2022-05-17 08:54 UTC, kostysh requested changes
Please review my comments on this PR.

2022-05-17 10:20 UTC, mfw78 commented
Please ensure that all commit messages follow conventional commit structure. Even 'fix' 👍

2022-05-17 10:40 UTC, bobetbat commented on packages/lpms-web/src/hooks/useGetAuth.ts
> +const API_URL = "http://localhost:8080/auth/";
✔️

2022-05-17 10:40 UTC, bobetbat commented on packages/lpms-web/src/hooks/useRefreshAuth.ts
> +const API_URL = "http://localhost:8080/refreshauth/";
✔️

2022-05-17 10:40 UTC, bobetbat commented on packages/lpms-web/src/store/reducer.ts
> +    token: '',
✔️

2022-05-18 08:26 UTC, kostysh commented on packages/lpms-web/.env.example
> +API_URL=http://localhost:5000
to be able to handle environment variables inside a React application, such variables must be prefixed with `REACT_APP_`

2022-05-18 09:32 UTC, bobetbat commented on packages/lpms-web/.env.example
> +API_URL=http://localhost:5000
✔️

2022-05-25 10:36 UTC, kostysh commented on packages/lpms-web/src/hooks/useRequest.ts
> +export const useRequest = ({ url, method, data }: {
we should not use an abstract name for this hook. The web application will use various types of request handlers so, I propose to rename this hook into `useAuthRequest`. This way it will be easy to specify other kinds of request handlers in the app.

2022-05-25 10:38 UTC, kostysh commented on packages/lpms-web/src/hooks/useRequest.ts
> +        }).then(async (res) => {
because we already use here `await` then it will be better to not use `then` and just split `then` chain into separate async calls.

2022-05-25 10:40 UTC, kostysh commented on packages/lpms-web/src/pages/PageWrapper.tsx
> +    if (authentication.token !== undefined && authentication.timestamp < Date.now() / 1000 - 30 * 60) {
I propose to move such definition (1000 - 30 * 60) into the `config` OR define it as `const` in the top of the file

2022-05-25 14:24 UTC, bobetbat commented on packages/lpms-web/src/hooks/useRequest.ts
> +export const useRequest = ({ url, method, data }: {
✔️

2022-05-25 15:18 UTC, bobetbat commented on packages/lpms-web/src/pages/PageWrapper.tsx
> +    if (authentication.token !== undefined && authentication.timestamp < Date.now() / 1000 - 30 * 60) {
✔️

2022-05-25 15:32 UTC, bobetbat commented on packages/lpms-web/src/hooks/useRequest.ts
> +        }).then(async (res) => {
✔️

2022-05-26 17:46 UTC, kostysh approved these changes

2022-05-26 17:46 UTC, merged